using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("Igor Brejc")]
[assembly: AssemblyProductAttribute("Detergent")]
[assembly: AssemblyCopyrightAttribute("")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCultureAttribute("")]
